# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\tonebullex\"9\n\x0b\x42\x61seMessage\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0c\n\x04time\x18\x03 \x01(\x03\"E\n\x11SendSubscribeInfo\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08platform\x18\x02 \x01(\t\x12\x0e\n\x06period\x18\x03 \x01(\t\"6\n\x12SendSubscribeDepth\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08platform\x18\x02 \x01(\t\"\'\n\x13SendSubscribeTicker\x12\x10\n\x08platform\x18\x01 \x01(\t\"w\n\tKlineInfo\x12\x0c\n\x04open\x18\x01 \x01(\x01\x12\r\n\x05\x63lose\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\x12\x0b\n\x03low\x18\x04 \x01(\x01\x12\x0e\n\x06volume\x18\x05 \x01(\x01\x12\x11\n\tstartTime\x18\x06 \x01(\x03\x12\x0f\n\x07\x65ndTime\x18\x07 \x01(\x03\"G\n\x0cRecKlineData\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12)\n\x0bkline_infos\x18\x02 \x03(\x0b\x32\x14.onebullex.KlineInfo\"*\n\tDepthInfo\x12\x0e\n\x06volume\x18\x01 \x01(\x01\x12\r\n\x05price\x18\x02 \x01(\x01\"U\n\x0cRecDepthInfo\x12!\n\x03\x62uy\x18\x01 \x03(\x0b\x32\x14.onebullex.DepthInfo\x12\"\n\x04sell\x18\x02 \x03(\x0b\x32\x14.onebullex.DepthInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BASEMESSAGE']._serialized_start=29
  _globals['_BASEMESSAGE']._serialized_end=86
  _globals['_SENDSUBSCRIBEINFO']._serialized_start=88
  _globals['_SENDSUBSCRIBEINFO']._serialized_end=157
  _globals['_SENDSUBSCRIBEDEPTH']._serialized_start=159
  _globals['_SENDSUBSCRIBEDEPTH']._serialized_end=213
  _globals['_SENDSUBSCRIBETICKER']._serialized_start=215
  _globals['_SENDSUBSCRIBETICKER']._serialized_end=254
  _globals['_KLINEINFO']._serialized_start=256
  _globals['_KLINEINFO']._serialized_end=375
  _globals['_RECKLINEDATA']._serialized_start=377
  _globals['_RECKLINEDATA']._serialized_end=448
  _globals['_DEPTHINFO']._serialized_start=450
  _globals['_DEPTHINFO']._serialized_end=492
  _globals['_RECDEPTHINFO']._serialized_start=494
  _globals['_RECDEPTHINFO']._serialized_end=579
# @@protoc_insertion_point(module_scope)
